//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMN_MAIN_ACTIVITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_COMN_MAIN_ACTIVITY()
        {
            this.T_COMN_SUB_ACTIVITY = new HashSet<T_COMN_SUB_ACTIVITY>();
        }
    
        public decimal ID { get; set; }
        public string ACTIVITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_COMN_SUB_ACTIVITY> T_COMN_SUB_ACTIVITY { get; set; }
    }
}
