//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMN_SUB_ACTIVITY
    {
        public decimal ID { get; set; }
        public Nullable<decimal> FK_MAINACTIVITY { get; set; }
        public string ACTIVITY { get; set; }
    
        public virtual T_COMN_MAIN_ACTIVITY T_COMN_MAIN_ACTIVITY { get; set; }
    }
}
